name: QA_Workflow_merge_group_33
on:
  merge_group:
    types: [checks_requested]
jobs:
  qa-job:
    runs-on: ubuntu-latest
    steps:
      - name: QA Step
        run: echo QA-Workflow original step
