name: QA_Workflow_discussion_comment_13
on:
  discussion_comment:
    types: [created]
jobs:
  qa-job:
    runs-on: ubuntu-latest
    steps:
      - name: QA Step
        run: echo QA-Workflow original step
