name: QA_Workflow_pull_request_review_comment_9
on:
  pull_request_review_comment:
    types: [created]
jobs:
  qa-job:
    runs-on: ubuntu-latest
    steps:
      - name: QA Step
        run: echo QA-Workflow original step
